### ISSUE TITLE
server failed to operate - crashes 

### ISSUE THREAD

**Issue by hgn** [protocollabs/maparo#33]
error message:

```
Closed network detected!
handleTcpConn goroutine called
panic: interface conversion: error is *errors.errorString, not *net.OpError

goroutine 35 [running]:
github.com/protocollabs/mapago/measurement-plane/tcp-throughput.(*TcpMsmtObj).tcpServerWorker(0xc000188000, 0xc000186120, 0xc0001860c0, 0x1b58, 0x1, 0xc00016c0f0, 0xc00018a1d0)                                                              
        /home/pfeifer/src/code/go/src/github.com/protocollabs/mapago/measurement-plane/tcp-throughput/server.go:149 +0x7bf                                                                                                                    
created by github.com/protocollabs/mapago/measurement-plane/tcp-throughput.NewTcpMsmtObj
        /home/pfeifer/src/code/go/src/github.com/protocollabs/mapago/measurement-plane/tcp-throughput/server.go:74 +0x382
```

**Comment by monfron** [comment]
Fixed by: https://github.com/protocollabs/mapago/commit/17699e8e2a341df10c248d92feea6288891218b5
